### ISSUE TITLE
As the data analysis tool, I want to perform statistical calculations on the data so that it can be passed to the report and visualization tools.

### ISSUE THREAD

**Issue by bglowniak** [bglowniak/Air-Quality-Analysis#22]
The core of our app's functionality. Once the data cleaning is complete, we can perform various analyses and compare the results to known reference values provided by our clients.

**Comment by bglowniak** [comment]
Scenarios and Acceptance Criteria (from our Semester 1 documents):

**Scenario:** Clean data is entered and analyzed properly
_Given_ the data has been cleaned and passed to the analysis phase
_When_ data is as the tool expects and analysis works as intended
_Then_ the tool will perform a statistical analysis of the data (including, but not limited to, checking for outliers and finding averages) and pass the results to the visualization phase

**Scenario:** One or many of the analysis processes fail
_Given_ the data has been cleaned and passed to the analysis phase
_When_ data values unexpectedly break the analysis formulas
_Then_ return an error message for said test to be displayed in the visualization but continue with the analysis for other data fields

**Scenario:** Humidity is unusually high (according to our client, this can distort the measurements)
_Given_ the data has been cleaned and passed to the analysis phase
_When_ the data is being analyzed and has a humidity higher than a threshold value
_Then_ set a flag value that will notify the visualization tool to make a remark about it in the output

**Scenario:** Specified important attributes pass a specific threshold (these elements and values have not been specified by our client yet, an example could be a certain particulate concentration is higher than healthy levels)
_Given_ the data has been cleaned and passed to the analysis phase
_When_ the data is being analyzed and a specific field has a value that is greater (or less) than a predefined threshold
_Then_ set a flag value that will notify the visualization tool to display an appropriate warning based on the value and field

**Comment by p13i** [comment]
@bglowniak From what I see, @jkatz35 has completed this task.

**Comment by bglowniak** [comment]
@p13i I think we were planning on adding a few more forms of statistical analysis for the final tool. Can @jkatz35 confirm?
