### ISSUE TITLE
As the visualization tool, I want to display data using static visualizations so that it can help the end user understand the processed data.

### ISSUE THREAD

**Issue by bglowniak** [bglowniak/Air-Quality-Analysis#23]
Once analysis is complete, we can begin generating the reports and visualizations that we will provide to our client. These will summarize our analyses and will compare the results to known reference values provided by our client.

**Comment by bglowniak** [comment]
Scenarios and Acceptance Criteria (from Semester 1 documents):

**Scenario:** One set of data is successfully validated and analyzed 
_Given_ the analysis tool has completed its functions successfully
_When_ the data is passed to the visualization function
_Then_ the tool will generate various static visualizations (bar graphs, scatter plots) of relevant information from the analysis

**Scenario:** Multiple sets of data are successfully validated and analyzed
_Given_ the analysis tool has completed its functions successfully for each dataset
_When_ the datasets are passed to the visualizations function
_Then_ the tool will generate various static visualizations that utilize all datasets

**Comment by p13i** [comment]
@bglowniak This was also done by @jkatz35, integration with the PDF script is almost done.
