### ISSUE TITLE
Improve Front-End Error Handling

### ISSUE THREAD

**Issue by bglowniak** [bglowniak/Air-Quality-Analysis#32]
Currently, if the backend tool errors, the front end does not present what happened to the user. The tool should create a dialog, display the error message, and then return to the start screen. This is an essential component of proper UI/UX design, and therefore must be completed by the final delivery.

**Comment by p13i** [comment]
@bglowniak : I attempted this in https://github.com/bglowniak/Air-Quality-Analysis/commit/fabcb4c5aa166397e23722994e76794df7f75ea6. Let me know if you think this can/should be done better/differently.

**Comment by bglowniak** [comment]
I think this is done. Back-end may need to return more descriptive errors though @jkatz35
