### ISSUE TITLE
Averaging Duration Front End

### ISSUE THREAD

**Issue by jkatz35** [bglowniak/Air-Quality-Analysis#37]
Change the Averaging Duration UI element to a number box and a drop down for the unit (Minutes, Hours, Days, Months). Pass to the back-end in the following format:
Two variables, the first containing the integer number, the second containing the string (e.g. Minutes, Hours, etc.)

**Comment by bglowniak** [comment]
Initial pass here a95e423a9dfdade2fb66a050d9609724f6193287
Waiting for some back-end changes to fully integrate

**Comment by bglowniak** [comment]
Front-end finalized in 2feede2bff1f4bab775806eea4c4b998540c732d and 63d5ae8321526ac78f7e4cd2e57d21cd7c99ff99. Back-end still making tweaks.
